### ISSUE TITLE
Unknown function: Trim

### ISSUE THREAD

**Issue by codeinabox** [mvolkmann/vim-react#1]
When trying to convert from a class to functional component I get the following error:

> Error detected while processing function ReactToggleComponent[6]..ReactFnToClass[82]..vru#DeleteLineIfBlank:
> line    1:
> E117: Unknown function: Trim
> E116: Invalid arguments for function len(Trim(getline(a:lineNum))) == 0)
> E15: Invalid expression: (len(Trim(getline(a:lineNum))) == 0)
>

**Comment by mvolkmann** [comment]
Thanks for reporting that! I'll try to address that by this coming weekend. Pretty swamped at the moment.

**Comment by mvolkmann** [comment]
I believe this issue is fixed now. Sorry it took me so long.
Can you please try the latest version and let me know if it works for you?

**Comment by codeinabox** [comment]
Thank you but I am unable to test it. For some reason none of the plugin's functions are working for me. I got `Plugin 'mvolkmann/vim-react'` in my .vimrc and it exists in the bundle directory. How can I verify it's installed correctly?

**Comment by mvolkmann** [comment]
I'm used to installing plugins using Pathogen. Do you use a different approach? If so and you can tell me what you use, maybe I can help.

---
R. Mark Volkmann
Object Computing, Inc.

**Comment by codeinabox** [comment]
Figured it out. Am able to toggle a component fine, thank you for the fix.
